logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
          client:
            requests: true
  observations:
    key-values:
      application: fraud-detection
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8081
spring:
  output.ansi.enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085
#        token-propagation: bearer
  thread:
    virtual:
      enabled: true
  application:
    name: fraud-detection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mysql
    url: jdbc:mysql://localhost:3306/fraud_detection
    username: root
  sql:
    init:
      mode: always
